messages:
  # When staff joins, this message displays. default: '&c[PLAYER FLAG] &eThere is currently &a{totalflags} active player flags. &7Use /playerflag for more information'
  staff-join: '&eThere is currently &a{totalflags} active player flags. &7Use /playerflag for more information'
  notification: '&c{player} &eflagged {target} &7: {message}'

# PERMISSIONS
# playerflag.cmd - gives general access to do /playerflag
# playerflag.notify - when a new playerflag is created, they are notified. And when a player joins with this permission, a message is displayed
# playerflag.create - can create a new playerflag by /playerflag create
# playerflag.remove - can remove a playerflag by /playerflag remove <nam-+e>11